# Generated by Django 3.1.3 on 2020-11-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputSequence', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField()),
                ('update_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Created'), (2, 'Processing'), (3, 'Success'), (4, 'Failed')], default=1, max_length=200)),
                ('created_on', models.DateTimeField()),
                ('update_on', models.DateTimeField()),
                ('input_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DNASequencer.searchrequest')),
            ],
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DNASequencer.user'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_name', models.CharField(max_length=200)),
                ('sequence_location', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DNASequencer.task')),
            ],
        ),
    ]
