# Generated by Django 3.1.3 on 2020-11-23 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DNASequencer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequest',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 18, 40, 59, 51297, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='update_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 18, 40, 59, 51322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 18, 40, 59, 51665, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 18, 40, 59, 51685, tzinfo=utc)),
        ),
    ]
