# Generated by Django 3.1.3 on 2020-11-23 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DNASequencer', '0002_auto_20201123_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequest',
            name='created_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 18, 47, 15, 581042, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='update_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 18, 47, 15, 581066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 18, 47, 15, 581413, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 18, 47, 15, 581429, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
